object Versions {
    const val kotlinVersion = "1.4.0"
    const val daggerVersion = "2.27"
    const val retrofitVersion = "2.9.0"
    const val okhttpVersion = "4.0.1"
    const val glideVersion = "4.9.0"
    const val materialVersion = "1.2.0-beta01"
    const val junitVersion = "4.12"
    const val androidxTestRunnerVersion = "1.3.0-alpha01"
    const val espressoCoreVersion = "3.3.0-alpha01"
    const val truthExtVersion = "1.3.0-alpha01"
    const val mockKVersion = "1.9.3"
    const val coreTestingVersion = "2.0.0"
    const val androidFragmentVersion = "1.4.1"
    const val constraintLayoutVersion = "2.1.3"
    const val pagingVersion = "3.1.1"
    const val swipeToRefreshVersion = "1.1.0"
    const val coroutinesTestingVersion = "1.4.3"
}